CREATE TABLE CUSTOMER
(
customerId NUMBER,
customerName VARCHAR(20),
PRIMARY KEY(customerId)
)

CREATE TABLE ACCOUNT
(
accountId NUMBER,
customerId NUMBER,
accountType VARCHAR(20),
balance NUMBER(10,3),
PRIMARY KEY(accountId),
FOREIGN KEY(customerId) REFERENCES CUSTOMER(customerId)
)

CREATE TABLE TRANSACTION
(
transactionId NUMBER,
accountId NUMBER,
transactionType VARCHAR(20),
transactionAmount NUMBER(10,3),
PRIMARY KEY(transactionId),
FOREIGN KEY(accountId) REFERENCES ACCOUNT(accountId)
)

CREATE TABLE ADDRESS
(
customerId NUMBER,
localCity VARCHAR(20),
localState VARCHAR(20),
localPincode VARCHAR(20),
homeCity VARCHAR(20),
homeState VARCHAR(20),
homePincode VARCHAR(20),
FOREIGN KEY(customerId) REFERENCES CUSTOMER(customerId)
)

DESCRIBE CUSTOMER
DESCRIBE ACCOUNT
DESCRIBE TRANSACTION
DESCRIBE ADDRESS


SELECT * FROM CUSTOMER
SELECT * FROM ADDRESS
SELECT * FROM ACCOUNT
SELECT * FROM TRANSACTION
DELETE FROM CUSTOMER

CREATE SEQUENCE CUSTID
INCREMENT BY 1
START WITH 100

CREATE SEQUENCE TRANID
INCREMENT BY 1
START WITH 1

CREATE SEQUENCE ACCID
INCREMENT BY 1
START WITH 50

DROP SEQUENCE CUSTID

SELECT CUSTID.CURRVAL FROM DUAL
 select CUSTID.nextval from dual;

ALTER SESSION SET CURRENT_SCHEMA =AKASH

DROP TABLE CUSTOMER
DROP TABLE ADDRESS
DROP TABLE TRANSACTION
DROP TABLE ACCOUNT