DROP TABLE EMPLOYEE;
DROP TABLE EVENT;
DROP TABLE REIMBURSEMENT;
DROP TABLE TOYEAR;

CREATE TABLE "EMPLOYEE"(
    "USERNAME" VARCHAR2(100 BYTE), 
    "PASSWORD" VARCHAR2(100 BYTE), 
    "TYPE" NUMBER(6,0), 
	"REPORTSTO" VARCHAR2(100 BYTE), 
	CONSTRAINT "EMP_PKEY" PRIMARY KEY ("USERNAME"),
	CONSTRAINT "NUM_RANGE" CHECK (type < 4 OR type >= 0), 
    CONSTRAINT "REPORTS_FK" FOREIGN KEY ("REPORTSTO")
    REFERENCES "PROJ1"."EMPLOYEE" ("USERNAME") ON DELETE CASCADE
);

CREATE TABLE "EVENT"(
    "NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"COVERAGE" FLOAT(9) NOT NULL, 
	"ID" NUMBER(9,0), 
    CONSTRAINT "COV_0100" CHECK (coverage > 0 AND coverage <= 1), 
	CONSTRAINT "ID_PK" PRIMARY KEY ("ID")
);

CREATE TABLE "REIMBURSEMENT" (
    "USERNAME" VARCHAR2(100 BYTE), 
	"SUBMITDATE" DATE, 
	"STARTDATE" DATE, 
	"URGENT" NUMBER(9,0), 
	"AMOUNT" NUMBER(9,0), 
	"EMPCOMMENT" VARCHAR2(1000 BYTE), 
	"SUPERVISOR" VARCHAR2(100 BYTE), 
	"SUPCOMMENT" VARCHAR2(1000 BYTE), 
	"DEPT" VARCHAR2(100 BYTE), 
	"DEPTCOMMENT" VARCHAR2(1000 BYTE), 
	"BENCO" VARCHAR2(100 BYTE), 
	"BENCOCOMMENT" VARCHAR2(1000 BYTE), 
	"SUPERAPP" NUMBER(6,0) DEFAULT 0, 
	"DEPTAPP" NUMBER(6,0) DEFAULT 0, 
	"BENCOAPP" NUMBER(6,0) DEFAULT 0, 
	"RID" NUMBER(9,0), 
	"REJECTED" NUMBER(6,0) DEFAULT 0, 
	"FINALAPP" NUMBER(6,0) DEFAULT 0, 
	"EVENT_ID" NUMBER(6,0), 
	"UPLOAD" BLOB, 
	CONSTRAINT "USERNAME_FK" FOREIGN KEY ("USERNAME")
	REFERENCES "PROJ1"."EMPLOYEE" ("USERNAME") ON DELETE CASCADE, 
    CONSTRAINT "EVENT_FK" FOREIGN KEY ("EVENT_ID")
    REFERENCES "PROJ1"."EVENT" ("ID") ON DELETE CASCADE 
);

CREATE TABLE "TOYEAR" (
    "USERNAME" VARCHAR2(100 BYTE) NOT NULL, 
	"MAXIMUM" NUMBER(9,0) DEFAULT 1000, 
	"PENDING" NUMBER(9,0) DEFAULT 0, 
	"AWARDED" NUMBER(9,0) DEFAULT 0, 
	UNIQUE ("USERNAME"),
    CONSTRAINT "USR_FK" FOREIGN KEY ("USERNAME")
    REFERENCES "PROJ1"."EMPLOYEE" ("USERNAME") ON DELETE CASCADE ENABLE
);
