CREATE TABLE EMPLOYEE(
"USERNAME" VARCHAR2(100 BYTE), 
"PASSWORD" VARCHAR2(100 BYTE), 
"TYPE" NUMBER(6,0), 
"REPORTSTO" VARCHAR2(100 BYTE),
 
 CONSTRAINT "EMP_PKEY" PRIMARY KEY ("USERNAME")
 CONSTRAINT "NUM_RANGE" CHECK (type < 4 OR type >= 0),
 CONSTRAINT "REPORTS_FK" FOREIGN KEY ("REPORTSTO")
 REFERENCES "PROJ1"."EMPLOYEE" ("USERNAME") ON DELETE CASCADE ENABLE
);

