--2.1
SELECT * FROM Employee;
SELECT * FROM Employee WHERE LASTNAME = 'King';
SELECT * FROM Employee WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
--2.2
SELECT * FROM Album ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM Customer ORDER BY CITY ASC;
--2.3
INSERT INTO GENRE (GENREID, NAME)
VALUES (26, 'Electronic');
INSERT INTO GENRE (GENREID, NAME)
VALUES (27, 'Disco');
INSERT INTO EMPLOYEE (EMPLOYEEID, FIRSTNAME, LASTNAME)
VALUES (9, 'BARRY', 'DAVIS');
INSERT INTO EMPLOYEE (EMPLOYEEID, FIRSTNAME, LASTNAME)
VALUES (10, 'CAROLINE', 'CAMERON');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL)
VALUES (60, 'EVANKA', 'OSMAK', 'EOSMAK@yahoo.com');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL)
VALUES (61, 'BARRY', 'DAVIS', 'BDAVIS@yahoo.com');
--2.4
UPDATE CUSTOMER
SET FIRSTNAME = 'Robert',
    LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';
UPDATE ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';
--2.5
SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';
--2.6
SELECT * FROM INVOICE WHERE TOTAL >= 15 AND TOTAL <= 30;
SELECT * FROM EMPLOYEE WHERE HIREDATE > '01-JUN-03' AND HIREDATE < '01-MAR-04';
--2.7
--DELETE FROM INVOICELINE INTERSECT SELECT INVOICEID FROM INVOICE WHERE CUSTOMERID = 32;
DELETE FROM INVOICELINE WHERE INVOICEID in (SELECT INVOICEID FROM INVOICE WHERE CUSTOMERID = 32);
DELETE FROM INVOICE WHERE CUSTOMERID = 32;
DELETE FROM CUSTOMER
WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter';

--3.0
SELECT CURRENT_TIMESTAMP FROM DUAL;
-- Audiotypes dont have lengths
--3.1

--7.0
--7.1
SELECT CUSTOMER.FIRSTNAME, CUSTOMER.FIRSTNAME, INVOICE.INVOICEID 
from CUSTOMER 
INNER JOIN INVOICE 
ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID;
--7.2
SELECT CUSTOMER.CUSTOMERID, CUSTOMER.FIRSTNAME, 
CUSTOMER.FIRSTNAME, INVOICE.INVOICEID,
INVOICE.TOTAL
from CUSTOMER , INVOICE
WHERE INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID;
--7.3
SELECT ARTIST.NAME, ALBUM.TITLE FROM ARTIST
RIGHT JOIN ALBUM
ON ARTIST.ARTISTID = ALBUM.ARTISTID;
--7.4
SELECT * FROM ALBUM
CROSS JOIN ARTIST
ORDER BY ARTIST.NAME;
--7.5
SELECT * FROM EMPLOYEE a
JOIN EMPLOYEE b
ON a.REPORTSTO = b.REPORTSTO;
/*
SELECT COUNT(A.REPORTSTO) FROM EMPLOYEE a
JOIN EMPLOYEE b
ON a.REPORTSTO = b.REPORTSTO
GROUP BY A.REPORTSTO
ORDER BY A.REPORTSTO;
*/