--2.1
SELECT * FROM Employee;
SELECT * FROM Employee WHERE LASTNAME = 'King';
SELECT * FROM Employee WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
--2.2
SELECT * FROM Album ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM Customer ORDER BY CITY ASC;
--2.3
INSERT INTO GENRE (GENREID, NAME)
VALUES (26, 'Electronic');
INSERT INTO GENRE (GENREID, NAME)
VALUES (27, 'Disco');
INSERT INTO EMPLOYEE (EMPLOYEEID, FIRSTNAME, LASTNAME)
VALUES (9, 'BARRY', 'DAVIS');
INSERT INTO EMPLOYEE (EMPLOYEEID, FIRSTNAME, LASTNAME)
VALUES (10, 'CAROLINE', 'CAMERON');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL)
VALUES (60, 'EVANKA', 'OSMAK', 'EOSMAK@yahoo.com');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL)
VALUES (61, 'BARRY', 'DAVIS', 'BDAVIS@yahoo.com');
--2.4
UPDATE CUSTOMER
SET FIRSTNAME = 'Robert',
    LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';
UPDATE ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';
--2.5
SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';
--2.6
SELECT * FROM INVOICE WHERE TOTAL >= 15 AND TOTAL <= 30;
SELECT * FROM EMPLOYEE WHERE HIREDATE > '01-JUN-03' AND HIREDATE < '01-MAR-04';
--2.7
SELECT * FROM INVOICELINE WHERE INVOICEID = (SELECT INVOICEID FROM INVOICE WHERE CUSTOMERID = 32);
SELECT * FROM INVOICE WHERE CUSTOMERID = 32;
DELETE FROM CUSTOMER
WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter';

--3.0
SELECT MAX(CURRENT_TIMESTAMP) FROM CUSTOMER;
-- Audiotypes dont have lengths
--3.1

